# Generated by Django 5.2.4 on 2025-07-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page_Visit',
            new_name='PageVisit',
        ),
    ]
